load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "logring",
    srcs = ["logring.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/logring",
    visibility = ["//:__subpackages__"],
)
