load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "guestrequest",
    srcs = ["types.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/winhcs/internal/protocol/guestrequest",
    visibility = ["//internal/winhcs:__subpackages__"],
)
