load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "logfields",
    srcs = ["fields.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/winhcs/logfields",
    visibility = ["//internal/winhcs:__subpackages__"],
)
