load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "timeout",
    srcs = ["timeout.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/winhcs/internal/timeout",
    visibility = ["//internal/winhcs:__subpackages__"],
)
