load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "queue",
    srcs = ["mq.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/winhcs/queue",
    visibility = ["//internal/winhcs:__subpackages__"],
)
