load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "opacl",
    srcs = ["opacl.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/opacl",
    visibility = ["//:__subpackages__"],
)
