load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testconfig",
    srcs = ["testconfig.go"],
    importpath = "github.com/bojanrajkovic/runny/internal/testconfig",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/home"],
)
